### ISSUE TITLE
Rettelser til setup

### ISSUE THREAD

**Issue by enerammer** [KUBDatalab/R-api_old#44]
Der skal konsekvens rettes for hvilke pakker der skal installeres.
Øverst står der at man skal installere tidyverse, og der står en tekst om tidyverse. Denne tekst skal udvides med info om "jsonlite", "zoo", "danstat".

I afsnittet 'For everyone' skal der tilføjes "zoo" i teksten over hvad der skal installeres

**Comment by chrbknudsen** [comment]
flyttet til ny udgave
