### ISSUE TITLE
Til "data visualisation with ggplot2"

### ISSUE THREAD

**Issue by enerammer** [KUBDatalab/R-api_old#51]
Virker som om denne tekst bør omformuleres

"Nice data. How does it look?

R has some nice plotting functions build in.

ggplot2 is a package with more, nicer, plotting possibilities.

We start by loading the required package. ggplot2 is also included in the tidyverse package."

**Comment by enerammer** [comment]
Er det blevet forklaret i sidste lesson, tidligere eller slet ikke "Remember from the last lesson that the pipe operator %>% "

**Comment by enerammer** [comment]
"We use the filter function - we have seen before. And it returns the rows in the data where the expression we write in the paranthesis is true." - bør måske også omformuleres

**Comment by chrbknudsen** [comment]
Flyttet til ny udgave
